### ISSUE TITLE
I would like to understand the formula

### ISSUE THREAD

**Issue by adamhongmy** [himelbrand/react-native-pixel-perfect#2]
Hi I reading thru your code and I notice your formula and I would like to understand it. 
Could you explain how this formula works to get the resolution?
`const DESIGN_RESOLUTION = Math.sqrt(designSize.height * designSize.height + designSize.width * designSize.width)`

**Comment by himelbrand** [comment]
@adamhongmy this isn't really the resolution, this is just the name I gave the variable.
`Math.sqrt(designSize.height * designSize.height + designSize.width * designSize.width)`
is actually the length of the diagonal of the screen...
This is true for any rectangle....

Actually the reason this works is because we use the ratio between the diagonals.

Note that this will work properly (tested on various devices) for sure when the screen is 16:9, however I cannot gurntee it will work for different screen ratios.

In my opinion, due to all of the new so called edge screens that have different ratios it might not be a perfect conversion.

If someone will open an issue on such a problem, I could sit and try and think how to do the conversion that is also dependant on the sceen ratio.

But from my own expirience (I havn't developed mobile apps in a long time) most of the curved or edge screens have different screen ratio than 16:9, but it is pretty close to that, meaning the conversion should still work in this cases for the naked eye. 

For example: Iphone X...

I hope this clears things up a bit.
